### ISSUE TITLE
SP2013: File names are not validated

### ISSUE THREAD

**Issue by andikrueger** [Nauplius/SharePoint-Patch-Script#1]
With SharePoint 2016 the file names of the patches are very unique. The script checks if there are matching files under the supplied path:
` $sts = Get-ChildItem -LiteralPath $Path | ?{$_.Name -match 'sts([A-Za-z0-9\-]+).exe'}`
` $wssloc = Get-ChildItem -LiteralPath $Path | ?{$_.Name -match 'wssloc([A-Za-z0-9\-]+).exe'}`

With SharePoint 2013 the file names do contain a pattern too (see: [SharePoint Patches](https://sharepointupdates.com/Patches)). Line 85 could be modified to:
`$patchfiles = Get-ChildItem -LiteralPath $Path | ?{$_.Name -match '([A-Za-z0-9\-]+)2013-kb([A-Za-z0-9\-]+)glb.exe'}`
This would prevent users from installing any .exe file which is found under the specified path.

SharePoint 2013 Patches named like "471445_intl_x64_zip.exe" would not be installed with this modification.

**Comment by tseward** [comment]
Change implemented, thank you!
