### ISSUE TITLE
Option to bypass detection

### ISSUE THREAD

**Issue by andreasblueher** [Nauplius/SharePoint-Patch-Script#13]
Hey, 

I just found your script as an updated version of the one I used for years. Yesterday I ran into the issue that I always received the message:

> The expected version of the product was not found on the system

It appears this is sometimes the case and can be [fixed ](https://social.technet.microsoft.com/Forums/en-US/dc83f0db-2928-4bf3-9228-86cf01c2f490/unable-to-install-sp1-for-sharepoint-designer-quotthe-expected-version-of-the-product-was-not?forum=sharepointadmin)by running sts file with

> PACKAGE.BYPASS.DETECTION.CHECK=1

as a parameter.

Could you please add this as an option to script, because I would love to use it, but I can't because the file (although it is correct) doesn't seem to be recognized.

Thank you
Andreas

**Comment by tseward** [comment]
That switch should never be used. Either the patch truly doesn't apply, or you have a partially patched farm. This means you should extract the patch and go through the MSPs one by one.

**Comment by andreasblueher** [comment]
Hello Trevor,

I've used this switch several times since it's the first post and accepted answer in Microsoft forums when you search for the error message.

Thanks for clearing things up for me.
