### ISSUE TITLE
Question: What about Content Databases?

### ISSUE THREAD

**Issue by DaleyKD** [Nauplius/SharePoint-Patch-Script#16]
I've been out of SharePoint for a couple years, but I thought we had to also run `Upgrade-SPContentDatabase` as part of the patch process.

If so, should this be a function in here?

Thanks!

**Comment by tseward** [comment]
You only run that if you're upgrading the databases prior to running the Config Wizard. The Config Wizard (psconfigui or psconfig) will update the databases.

Certain orgs choose to upgrade databases first for timing purposes.

**Comment by DaleyKD** [comment]
Thanks for the info, man.  I didn't realize that PSConfig did it for us.
