### ISSUE TITLE
Path for PSConfig isn't always found

### ISSUE THREAD

**Issue by DaleyKD** [Nauplius/SharePoint-Patch-Script#17]
When using `Invoke-SPConfigWizard`, on one of my machines, I received `The term 'PSConfig.exe' is not recognized as the name of a cmdlet ...`.

For what it's worth, my personal .ps1 ran the same thing as yours, and it was gave me the same issue.  I had to use `Test-Path` to see if it existed in the 15 or 16 hive, then use that to give a full path for PSConfig.exe.

**Comment by DaleyKD** [comment]
Strange.  After a reboot, it worked the next time.

**Comment by tseward** [comment]
The path is part of the system environment variables/SharePoint Management Shell so that is unusual that it wouldn't be found, but would explain why a reboot would 'fix' it.

The psconfig path was first added as part of SharePoint 2010.
