### ISSUE TITLE
Request: Publish this to PowerShell Gallery

### ISSUE THREAD

**Issue by DaleyKD** [Nauplius/SharePoint-Patch-Script#18]
When trying to write an internal "how to," it'd be so easy to have the user just use:

```powershell
Install-Module SharePointPatchScript
```

**Comment by tseward** [comment]
Agreed. Need to find a good guide for it.

**Comment by tseward** [comment]
Published at https://www.powershellgallery.com/packages/SharePointPatchScript

**Comment by DaleyKD** [comment]
If you find a chance, maybe you can update your Wiki.

My internal Wiki now uses `Install-Module SharePointPatchScript`.

Thank you **so** much.

**Comment by tseward** [comment]
Thanks for the reminder -- updated.
