### ISSUE TITLE
Exit Code forcing reboot

### ISSUE THREAD

**Issue by ErikBoSo** [Nauplius/SharePoint-Patch-Script#2]
Hi,
Great script.
I was just wondering: shouldn't Exit Code **17022** (Success: Reboot flag set) be added to the check for Exit Code == 3010?
Kind regards and thank you for sharing.
Bo

**Comment by tseward** [comment]
I was working off of the Office exit codes as defined at https://technet.microsoft.com/en-us/library/cc179058%28v=office.14%29.aspx. If you're seeing 3010, then yes we should accommodate that.
