### ISSUE TITLE
Multiple Files on SharePoint 2013

### ISSUE THREAD

**Issue by abhijitbossotto** [Nauplius/SharePoint-Patch-Script#4]
Hi 
I got 2 files in my Patches Directory:
ubersrv2013-kb4018302-fullfile-x64-glb
ubersts2013-kb4018299-fullfile-x64-glb
But i seems that the Script only install the one with the lower number (kb4018299). What should I do to install both at the same time with the script? 
Thanks for a Tipp :-)
Abi

**Comment by tseward** [comment]
You only need to install https://support.microsoft.com/sw-ke/help/4018302/march-13-2018-cumulative-update-for-sharepoint-enterprise-server-2013. That takes care of the Foundation update.
