### ISSUE TITLE
Stopping Search Services before Timer Service

### ISSUE THREAD

**Issue by justin-castleman** [Nauplius/SharePoint-Patch-Script#5]
I have read many places that it is advised to stop the Timer Service before you stop the search service. This is due to the fact that the Timer Service will try and start the search service if it sees it stopped. Is this taken care of by the fact that the script disables the search service rather than just stopping it?

**Comment by tseward** [comment]
It is the Search Host Controller that starts the Search Service if it sees it in a stopped state, not the SharePoint Timer service. Hope that helps!
