### ISSUE TITLE
Script enables search services on hosts that don't run search

### ISSUE THREAD

**Issue by SHRPNT247** [Nauplius/SharePoint-Patch-Script#6]
The script is enabling and attempting to start OSearch and SpSearchHostController regardless of whether they were originally running or not on SP2013. 
        ###Ensuring Search Services were stopped by script before Starting" 
        if($Stop -or $Pause) 
This comment is not correct, if($Stop -or $Pause) is always true due to the parameter definition. 

In testing I found that SharePoint stops the services after a short time and a timer job sets it back to disabled after a hour or so it doesn't seem to leave a permanent issue on the farm. 

My suggestion to correct this issue is the following:
#Create variable to track if search services were stopped
**$searchSvcRunning = $false**
...
    if(($oSearchSvc.status -eq 'Running') -or ($sPSearchHCSvc.status-eq 'Running')) 
    { 
        **$searchSvcRunning = $true**
...
        ###Replace $Stop -or $Pause with $searchSvcRunning
 if(**$searchSvcRunning**) 
        { 
            Set-Service -Name "OSearch$majorVersion" -StartupType Manual 
...

**Comment by tseward** [comment]
Thanks, I will take a look at this.
