### ISSUE TITLE
Stop search need also for sp2016/2019 maybe ?

### ISSUE THREAD

**Issue by paololec** [Nauplius/SharePoint-Patch-Script#9]
According to: https://docs.microsoft.com/en-us/sharepoint/upgrade-and-update/install-a-software-update#HostSearch
Seems that also for sp2016 and sp2019 need stop/disable OSearch, SPSearchController and SPTimerV4. 
So the if($majorVersion -lt '16') is to apply only for IISAdmin e iisreset scrip part ??

**Comment by tseward** [comment]
I'll get clarity from the PG on this, but unlike 2013 and below, the service portion is taken care of for you -- the only thing you should need to explicitly do is pause the SSA(s).

**Comment by tseward** [comment]
FYI this doesn't need to be stopped at the service level.
